// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMKoc_lDKZ7LMc6ocRxC_NRQYNjlMm-A0',
    appId: '1:257399228421:web:a76950a1f499208a48f46c',
    messagingSenderId: '257399228421',
    projectId: 'diss-8de2e',
    authDomain: 'diss-8de2e.firebaseapp.com',
    storageBucket: 'diss-8de2e.appspot.com',
    measurementId: 'G-D5DW24PZC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOfcEdWe-7AcLrZVEbfCP8yQNrk5Jv3g',
    appId: '1:257399228421:android:df771c9eca9c7cbf48f46c',
    messagingSenderId: '257399228421',
    projectId: 'diss-8de2e',
    storageBucket: 'diss-8de2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2BmATuhh3APvzKyxCyX0TWnSuBQTuqg',
    appId: '1:257399228421:ios:562efade676ec78448f46c',
    messagingSenderId: '257399228421',
    projectId: 'diss-8de2e',
    storageBucket: 'diss-8de2e.appspot.com',
    iosBundleId: 'com.example.diss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2BmATuhh3APvzKyxCyX0TWnSuBQTuqg',
    appId: '1:257399228421:ios:1ba219b5ef1761bc48f46c',
    messagingSenderId: '257399228421',
    projectId: 'diss-8de2e',
    storageBucket: 'diss-8de2e.appspot.com',
    iosBundleId: 'com.example.diss.RunnerTests',
  );
}
